services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    command: php artisan octane:start

    pull_policy: always

    post_start:
      - command: npm run build
      - command: php artisan optimize
    pre_stop:
      - command: php artisan octane:stop

    ports:
      - '8000:8000'

    volumes:
      - lvdata:/app/storage
    env_file:
      - ./.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/up']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel
#     command: php artisan serve

#     volumes:
#       - lvdata:/app/storage
#     env_file:
#       - ./.env

#     ports:
#       - '8000:8000'

#     healthcheck:
#       test: ['CMD', 'curl', '-f', 'http://localhost:8000']
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 10s

volumes:
  lvdata:
